Task 3
AnnLiz22/invoicing-system-anna-lietz pull request #3
Opened 2023-03-27 20:54 UTC by AnnLiz22

Zadanie 3 do sprawdzenia

2023-03-29 19:36 UTC, patryk-stepniak requested changes
Dodatkowe uwagi:
1. Brakuje testów
2. Checkstyler rzuca błędami, a mimo to build przechodzi. Oznacza to, że masz błędy w konfiguracji projektu.
3. Jacoco nie sprawdza pokrycia testami. Przyczyną tego jest również błędna konfiguracja projektu.
4. PR zawiera konflikty.

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/db/FileDatabase.java
> +//@AllArgsConstructor
Zakomentowany kod

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/db/FileDatabase.java
> +public void save(Invoice invoice) {
Formatowanie (brak tabulacji).

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/db/FileDatabase.java
> +  List<Invoice> invoices = getAll();
Operacja dodania nowego elementu nie powinna wymagać pobrania wszystkich elementów. FileService powinien mieć możliwość dopisania tylko jednej linii do pliku.

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/db/FileDatabase.java
> +    List<Invoice> invoices = getAll();
A co jeśli ktoś poda niepoprawny Id? Przydałby się jakiś komunikat, a w obecnej sytuacji metoda się wykona i ciężko będzie zauważyć problem.

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/db/memory/InMemoryDatabase.java
> +    //  return nextId++;
Zakomentowany kod

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/service/FileService.java
> +public class FileService {
Formatowanie klasy

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/service/FileService.java
> +    try {
Zamiast obsługiwać IOException tutaj, lepiej przekazać obsługę tego wyjątku wyżej, do serwisu. Robimy tak, ponieważ tutaj nie mamy pojęcia jak obsłużyć ten wyjątek (samo przechwycenie go i ponowne wyrzucenie to mało). Przy tej implementacji nie będziemy wiedzieli, w którym momencie ten błąd poleciał (czy podczas zapisu nowego obiektu do bazy, czy odczytu, update'u i tak dalej).

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/service/FileService.java
> +      System.out.println("error while reading data from file: " + e);
Jak wyżej

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/service/FileService.java
> +      return objectMapper.readValue(new File(filename), type);
FileSevice nie powinien zajmować się mapowaniem tekstu na obiekty. Od tego mamy JsonService. Ten service powinien tylko i wyłącznie zapisywać dane do pliku i je odczytywać (w formie Stringa).

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/service/FileService.java
> +  public void writeDataToFile(String fileName, Object object){
FileSevice nie powinien zajmować się mapowaniem tekstu na obiekty. Od tego mamy JsonService. Ten service powinien tylko i wyłącznie zapisywać dane do pliku i je odczytywać (w formie Stringa).

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/model/Company.java
> +  public Company(String taxIdentificationNumber, String address, String name) {
@AllArgsConstructor

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/model/Vat.java
> +  ;
,;

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/service/InvoiceService.java
> +
coś tu pusto

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/service/JsonService.java
> +      return
formatowanie

2023-03-29 19:36 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/service/JsonService.java
> +public class JsonService {
Nigdzie nie używasz tej klasy.

2023-05-03 19:23 UTC, strzeleckik approved these changes
ok ;)

2023-05-04 06:38 UTC, merged